default: &default
  encoding:  utf8mb4
  charset:   utf8mb4
  collation: utf8mb4_unicode_ci
  adapter:   "mysql2"
  encoding:  "utf8"
  username:  root
  password:
  timeout:   5000

development:
  <<: *default
  database: rails
  host: mysql

test:
  <<: *default
  database: rails-test
  host: mysql
